### ISSUE TITLE
[b] 신기능 option 구현요청

### ISSUE THREAD

**Issue by ss35789** [Team-Discipline/Xlack-Backend#12]
![image](https://user-images.githubusercontent.com/55543713/179158096-4d85e3a0-c779-4a03-a6c0-bd0cbdf61732.png)

**Comment by kreimben** [comment]
@ryankimjh00 

멘션 기능 구현 안됨
저장된 포스트 CRD기능 구현 안됨
people은 가입된 유저 프로필만 보이게
apps, channel browser는 뭔지 모르겠음
file browser는 업로드 된 파일만 보이게 해주는 것인데 구현 안됨.

일단 실시간채팅 기능 구현 다 하고 나중에 멘션 기능은 따로 기능 회의 좀 해야할듯...

**Comment by ryankimjh00** [comment]
@kreimben got it👍
