### ISSUE TITLE
고도화 작업 준비

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Backend#17]
@ryankimjh00 

고도화 작업 내용 중에 다른건 상관없는데, 깜빡하고 기능 추가 안한게 있는데
channel, chat중에 auth check 작업 안한거였더라고.

channel이나 chat가져다 쓰려면 로그인이 됐는지 확인을 해봐야하니깐 거기에 Depends로 작업 해줘야하는 부분이 있는데,
channel하고 chat 작업이 끝나면 해당 부분 git commit hash알려주기 바람.

나머지는 내가 알아서 작업해둘께.

**Comment by ryankimjh00** [comment]
옙!

**Comment by ryankimjh00** [comment]
Channel&Chat Authorization check code complete. Hash is here `c4eb014cf4139880c4c4bd174eba62ed07e137aa`

**Comment by kreimben** [comment]
Really thanks.
