### ISSUE TITLE
What method?

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Backend#18]
https://github.com/Team-Discipline/Xlack-Backend/blob/c4eb014cf4139880c4c4bd174eba62ed07e137aa/app/channel/router.py#L15

데코레이터 부분만 간략히 답장해주면 추가할게
@ryankimjh00

**Comment by kreimben** [comment]
get_auth도 틀렸음. 알아서 수정할게.

**Comment by ryankimjh00** [comment]
엇..알겠어

**Comment by kreimben** [comment]
아니 channel router.py 코드 왜 이렇게 됐냐
제대로 돌아가는 코드가 없어 보이는데....?

**Comment by kreimben** [comment]
나머지 전부다 수정해 둘게.

**Comment by ryankimjh00** [comment]
엥 잠시만 확인좀 해볼게
