### ISSUE TITLE
Chat 객체 건의

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Backend#20]
Chat 객체에 channel_id를 foreign_key 처리해서 channel id도 같이 알려주는편이 좋지 않을까 싶긴 한데...

의견 알려주기 바람.

**Comment by ryankimjh00** [comment]
@kreimben 아 어떤 chat이 어떤 channel에 속해있는지 정보를 줘서 불러오기 편하게 하자는거야?

**Comment by kreimben** [comment]
chat history는 txt로 저장할 필요가 없지...
마리아db에 모델 정의하고 crud쪽에 함수 짜서 다른것들 처럼 해야지....

**Comment by kreimben** [comment]
그러니깐 websocket으로 실시간으로 받는거 하나,
전체 메세지 pagination처리 해서 가져오는 api하나 이렇게 개발해야지.

**Comment by kreimben** [comment]
내가 말한거는 이제 websocket이랑 전체메세지 가져오는 디자인을 어떻게 할꺼냐, 생각해둔거 있냐 그걸 물어본거고...

**Comment by kreimben** [comment]
> @kreimben 아 어떤 chat이 어떤 channel에 속해있는지 정보를 줘서 불러오기 편하게 하자는거야? 안그래도 chat history 저장하는 함수에서 .txt 파일에 저장할때 channel id도 같이 넣어주는 걸로 해놓긴 했는데

그리고 chat객체를 받을때 프론트 쪽에서 '이게 어느 채널에 있는 채팅인지 알 수 있으면 좋지 않을까' 하는걸 미리 생각해둔 차원에서 얘기한거고.

**Comment by kreimben** [comment]
근데 우리 실시간 채팅이랑 그냥 chat으로 구현된거랑 무슨 차이지...?

**Comment by ryankimjh00** [comment]
그냥 chat으로 구현된건 새로운 유저가 실시간으로 채팅에 참여할 수가 없는데 websocket으로 실시간채팅 만들면 페이지를 새로 생성해서 로그인할때마다 유저가 계속 그 채팅을 공유가 가능한거..?가 차이 아닐까?? 우리가 만들어놓은 채팅은 그냥 일방적이잖아 이메일처럼

**Comment by ryankimjh00** [comment]
그렇지 따로 처리해놨어!

**Comment by kreimben** [comment]
그래 그러면 RealChat으로 따로 구현 했던거 chat으로 합치자

**Comment by ryankimjh00** [comment]
OK!👌 근데 나 일이 있어서 지금 밖이라 오늘 밤~내일 동안에 합쳐서 커밋해놓을게

**Comment by kreimben** [comment]
Chat 객체에는 channel_id 필드 넣지 않기로함.

대신 ChatHistory라는 객체(테이블) 별도로 만들어 그 곳에 채팅 히스토리 기록하게 구현.
FIle객체(테이블)역시 마찬가지.

**Comment by kreimben** [comment]
move to https://github.com/Team-Discipline/Xlack-Backend/issues/27
