### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Backend#29]
멘션기능, 채팅기능 둘중에 하나는 금요일 미팅 전까지 구현 완료 후 Pull Request 해주세요.

@ryankimjh00

**Comment by ryankimjh00** [comment]
@kreimben 아 옙~!

**Comment by ryankimjh00** [comment]
@kreimben 엇 다시 확인해보니 자동으로 pull request 되었습니다.
