### ISSUE TITLE
Django Migration Plans

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Backend#31]
1. 기존 FastAPI는 모두 정리 후 fastapi_version 브랜치로 이동.
2. develop 브랜치 신설 후 그 곳에 장고 준비.
3. 장고 app들의 경우 features/로 (기존과 같이) 세분화
4. main, deploy브랜치는 장고 개발 중 머지.
@ryankimjh00

**Comment by kreimben** [comment]
features (app)

How to make django apps: in venv `django-admin startapp {FEATURE}`

In project `settings.py`, You should add your app in `INSTALLED_APPS`

**Comment by kreimben** [comment]
App Lists

- [ ] authentication -> alter to django admin.
- [ ] authorization -> alter to django admin.
- [ ] user -> alter to django admin. -> Should custom user model to save user information.
- [ ] channel
- [ ] chat -> with django channels.
- [ ] file -> file uploading.


@ryankimjh00

**Comment by ryankimjh00** [comment]
@kreimben 확인완료!

**Comment by kreimben** [comment]
- [ ] Custom User model -> @ryankimjh00 
 - [ ] github oauth2 connection -> @ryankimjh00 
 - [ ] (later) notification -> django messages -> @kreimben

**Comment by kreimben** [comment]
API 변경사항

* 기존 fastapi는 `https://xlack.kreimben.com/api`에서 `https://xlack.kreimben.com/old/api`로 이동.
* 기존 `/authentication`부분은 없어짐. -> 로그인 시 새로운 `/token/github/` 또는 `/token/github/connect/`를 사용해야함.
* 기존 `/authentication/github_login`에서 oauth url줬는데 삭제함. -> frontend에서 알아서 처리하도록. -> `https://github.com/login/oauth/authorize?client_id=9ac10cd868488ad0185b&scope=read:user` 수동으로 들어가기.
* 기존 `/authentication/user_check`, `/authentication/issue_tokens`, `/user/`는 삭제됨 -> 새로운 `/token/github/`에서 모두 담당.
* 새로운 `/token/github/`에서 스웨거 문서에 나와있는대로 처리할 것.
* 기존 `/authorization/` 완전 삭제 -> 더 이상 프론트엔드에서 처리할 필요가 없어졌음.
* 기존 `/channel/all`는 삭제 -> 새로운 `/channel/`가 전담. -> 나머지 채널 관련 엔드포인트는 융통성 있게~
* 기존 `user`관련 완전 삭제 -> 새로운 `/profile/`에서 깃헙과 연관된 프로필을 받아오기.
* 기존 `chat`변경 -> 새로운 `/chat/`은 채팅 내역을 보여줌.


새로운 점

* 로그아웃 처리하는 POST `/accounts/logout/`
* 엑세스 토큰 재발급 하는 `/accounts/token/refresh/` -> 반드시 리프레시 토큰을 이용해야하며, 리프레시 토큰 rotaion을 적용해 놨기 때문에, 새롭게 at, rt 쿠키에 저장해야함.
* 토큰들이 유효한지 검사하는 `/accounts/token/verify/` -> 이거 쓰면 응답 없이 200코드만 뜨는데, 정상임.
* 지금 유저 정보 (프로필 제외) 조회하는 `/accounts/user/`.
* 나머지  `/accounts/` 관련 엔드포인트 들은 사용할 필요가 없음.

필요 없는 부분은 나중에 삭제 될 수도 있으니 사용하지 말것.
