### ISSUE TITLE
Channel All 500 Error

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Backend#32]
![image](https://user-images.githubusercontent.com/20333172/182762696-0fc3148d-83b7-4746-9100-9798a6931d78.png)

@ryankimjh00 

`GET /channel/all` 500에러 뜹니다.
확인 부탁드립니다.

**Comment by kreimben** [comment]
https://github.com/Team-Discipline/Xlack-Frontend/issues/26
sidebar.tsx에서 에러나는 부분.

**Comment by kreimben** [comment]
@ryankimjh00 수정후 PR.

**Comment by ryankimjh00** [comment]
@kreimben 넵!~

**Comment by ryankimjh00** [comment]
@kreimben 혹시 이전에 deploy에서는  channel all 에러는 없었나요? 아무래도 지금 features/chat 브랜치에 있는 코드가 deploy로 안넘어간거 같습니다. 제 코드(channel/router.py)만 돌려봤을때는 아무 에러도 없습니다. 일단 지금 있는 코드 머지해보겠슴다,

**Comment by kreimben** [comment]
@ryankimjh00 

![image](https://user-images.githubusercontent.com/20333172/182841660-52fccd0a-d43d-4d5a-9b09-6d9dcf603183.png)


아직도 안됨

**Comment by ryankimjh00** [comment]
@kreimben 와 에러가 바뀌어버렸네..확인
