### ISSUE TITLE
 Emergency

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/Xlack-Backend#35]
@kreimben 
비상! 지금 왠지 에러도 안뜨고 된거같아! 그래서 migration만 하면 되는데
<img width="434" alt="image" src="https://user-images.githubusercontent.com/85392646/183405069-478ff10c-810b-4e0d-ae4f-38a3f137d6c5.png">
지금 계속 이런 상태고 `user_custom`에 migration파일 지우고 `python manage.py makemigration user_custom` 하면 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/85392646/183405285-a17a5251-51e4-4883-a4c1-7bc1e7c9f4bb.png">
에러 안뜨고 잘되긴 하는데
이렇게 runserver 해보면 
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/85392646/183405465-ea25fc88-3235-4983-9147-7d7fba9df4eb.png">
라고 떠..helpme..(error msg = `django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency user_custom.0001_initial on database 'default'.`)

last commit : `27115f5b2417d30ec3dfb59e129734e678c5c7cc`

**Comment by ryankimjh00** [comment]
> 

@kreimben 근데 stackoverflow랑 여러개 찾아봤는데 다 db을 엎어야 된다고 해서 무서워서 그 방법은 못하는중

**Comment by kreimben** [comment]
@ryankimjh00  내가 처리한 migrations이랑 니가 하려는 migrations이랑 버전이 곂쳐서 그럴꺼야
내꺼 features/chat에서 migrations가져가 (git cherry pick)

**Comment by ryankimjh00** [comment]
> @kreimben thanks!

**Comment by kreimben** [comment]
https://github.com/Team-Discipline/Xlack-Backend/pulls
PR로 대체.
