### ISSUE TITLE
[b] chat reaction

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Backend#65]
1. 기능 이름: chat reaction
2. 구현 담당자: @ds1sqe 
3. 작업 시작일: 2023-01-05
4. 작업 완료일: 2023-01-06 예정 / 2023-01-29 완료

세부 구현 사항 아래링크 참조
https://github.com/orgs/Team-Discipline/projects/1/views/1?pane=item&itemId=17416515

**Comment by ds1sqe** [comment]
# Reaction

- [] 1. Models

  have to create table,
  which contains

  a. the id of chat,
  b. users that have reacted
  c. the reaction

  data hierarchy

  Chat->Reaction(nullable, many)

  Chat {
  id
  message
  file
  chatter
  channel
  created_at
  reaction (Many){
  reacted user
  reaction
  }
  }

- [] 2. Internal Algorithm

  1. refresh reaction (Get)
     a. just get whole reaction over channel

  2. Creating reaction (Post)
     a. if reaction exist, add member
     else, create
     b. send the reaction to channel member

  3. Update or Delete reaction (Post)
     a. if reaction don't exist, Throw Error
     else, update.
     -> It was last? then delete
     b. send the reaction to channel member

- [] 3. Endpoint

  the user will retreive data on connect,
  and, if someone changed reaction on a chat,
  send the data directly over channel

  endpoint 1. ws 2. REST

  a. refresh
  b. update or create
  c. delete

- [] 4. The "Data"

  a. Post
  { (User->Server)

      0. chat id
      1. who was reacted
      2. reaction icon
      3. Maybe type?

  }

  b. GET
  { (Server->User)

      0. chat's id
      1. reaction's members
      2. reaction's number(count)
      3. reaction's unicode

  }
